CFLAGS=-g
all: 1.out 1b.out 2.out 2b.out 3.out 3b.out 4.out 4b.out 5.out 5b.out 6.out
1.out: 1.c
	gcc -g -o 1.out 1.c
2.out: 2.c
	gcc -g -o 2.out 2.c
3.out: 3.c 
	gcc -g -o 3.out 3.c
4.out: 4.c
	gcc -g -o 4.out 4.c -lpthread
5.out: 5.c
	gcc -g -o 5.out 5.c
6.out: 6.c
	gcc -g -o 6.out 6.c
1b.out: 1b.c
	gcc -g -o 1b.out 1b.c
2b.out: 2b.c
	gcc -g -o 2b.out 2b.c
3b.out: 3b.c 
	gcc -g -o 3b.out 3b.c
4b.out: 4b.c
	gcc -g -o 4b.out 4b.c -lpthread
5b.out: 5b.c
	gcc -g -o 5b.out 5b.c

